model:
  resolutions_list: [32, 16, 8, 4]
  in_channels: 1
  out_channel_multipliers: [1, 2, 4, 8]
  starting_channels: 64
  num_resnet_blocks: 2
  attention_resolutions: [16]
  T: 1000
  T_dim: 256
  learned_variance: True

train:
  lr : 0.0001
  epochs: 50
  batch_size: 64
  loss: 'noise_predictor_loss'
  checkpoint_folder: '../checkpoints/'
  checkpoint_path: '../checkpoints/nem_model_epoch_50.pth'
  allowed_classes: [1,2,3]

diffusion_params:
  beta_1: 0.0001
  beta_T: 0.02
  T: 1000
