model:
  resolutions_list: [32, 16, 8, 4]
  in_channels: 1
  out_channel_multipliers: [1, 2, 4, 8]
  starting_channels: 64
  num_resnet_blocks: 2
  attention_resolutions: [16]
  T: 1000
  T_dim: 256

train:
  lr : 0.0001
  epochs: 50
  batch_size: 32
  loss: 'score_matching_loss'
  checkpoint_folder: '../checkpoints_score_matching/'
  checkpoint_path: '../checkpoints/model_epoch_conditional_20.pth'
  allowed_classes: [1,2,3]
  use_guidance: True
  label_drop_prob: 0.2

diffusion_params:
  beta_1: 0.0001
  beta_T: 0.02
  T: 1000
